name: Build and PR Workflow

on:
  workflow_dispatch:
    inputs:
      snapshot_version:
        description: 'Enter the SNAPSHOT build version'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a new branch
        run: |
          git checkout -b dynamic-vars-tasks
          git push origin dynamic-vars-tasks

  update-version:
    runs-on: ubuntu-latest
    needs: create-branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: dynamic-vars-tasks
          fetch-depth: 0

      - name: Update SNAPSHOT Version in POM.xml
        run: |
          sed -i 's/<version>.*<\/version>/<version>${{ github.event.inputs.snapshot_version }}<\/version>/g' pom.xml
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add pom.xml
          git commit -m "Updated POM version to ${{ github.event.inputs.snapshot_version }}"
          git push origin dynamic-vars-ttasks

  build:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: dynamic-vars-tasks
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Project
        run: |
          mvn clean install

      - name: Create a Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          branch: dynamic-vars-tasks
          title: 'Update SNAPSHOT Version and Build'
          body: 'This PR updates the POM.xml to the new SNAPSHOT version: ${{ github.event.inputs.snapshot_version }} and performs a build.'
          base: main
