name: Build and PR with CodeQL Scan/Update

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Snapshot build version'
        required: true

jobs:
  update-pom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update version for swagger-petstore in pom.xml
        run: |
          sed -i -E '/<artifactId>swagger-petstore<\/artifactId>/,/<\/version>/ s|<version>[0-9.]*</version>|<version>${{ github.event.inputs.version }}</version>|' pom.xml

      - name: Commit and push version change
        run: |
          git add pom.xml
          git commit -m "Update version to ${{ github.event.inputs.version }}"
          git push origin master

  codeql-scan:
    needs: update-pom
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  merge-pr:
    needs: codeql-scan
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Merge Pull Request
        run: |
          gh pr merge update-version-${{ github.event.inputs.version }} --merge
