name: Full CI/CD Pipeline

on:
  push:
    branches:
      - dynamic-vars-tasks
  workflow_dispatch:
    inputs:
      snapshot_version:
        description: 'SNAPSHOT build version'
        required: true
        type: string
  pull_request:
    branches:
      - master

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Update version in POM.xml
      run: |
        sed -i 's/<version>.*<\/version>/<version>${{ github.event.inputs.snapshot_version }}<\/version>/g' pom.xml
    
    - name: Commit and Push changes
      run: |
        git add pom.xml
        git commit -m "Update version in pom.xml" || echo "No changes to commit"
        git push origin dynamic-vars-tasks
  
    - name: Maven Build
      run: mvn clean install

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v3
      with:
        branch: dynamic-vars-tasks-1.2
        base: master
        title: "Update to ${{ github.event.inputs.snapshot_version }}"
        body: "This pull request updates the version and builds the project."

  codeql-analysis:
    needs: build-and-update
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  auto-merge:
    needs: codeql-analysis
    if: github.event.pull_request.head.ref == 'dynamic-vars-tasks'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge PR
      uses: "peter-evans/enable-pull-request-automerge@v2"
      with:
        pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
        merge-method: "squash"