name: Full CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      snapshot_version:
        description: 'SNAPSHOT build version'
        required: true
        type: string
  pull_request:
        branches: master

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create new branch
      run: 
        git checkout -b dynamic-vars-tasks
        git push origin dynamic-vars-tasks

    - name: Update version in POM.xml
      run: 
        sed -i 's/<version>.*<\/version>/<version>1.0.1-SNAPSHOT<\/version>/g' pom.xml
    - name: Commit and Push changes
      run: 
        git add pom.xml
        git commit -m "Update version in pom.xml"
        git push
  

    - name: Maven Build
      run: mvn clean install

    - name: Create Pull Request
      id: create-pr
      uses: create-pull-request@v3
      with:
        branch: dynamic-vars-tasks
        base: master
        title: "Update to ${{ github.event.inputs.snapshot_version }}"
        body: "This pull request updates the version and builds the project."

  codeql-analysis:
    needs: build-and-update
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  auto-merge:
    needs: codeql-analysis
    if: github.event.pull_request.head.ref == 'dynamic-vars-tasks'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Merge PR
    #   run: |
    #     git fetch origin dynamic-vars-tasks
    #     git merge --ff-only origin/dynamic-vars-tasks
    #     git push origin main
