name: Full CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      snapshot_version:
        description: 'SNAPSHOT build version'
        required: true
        type: string
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create new branch
      run: |
        git checkout -b dynamic-vars-tasks
        git push origin dynamic-vars-tasks

    - name: Update version in POM.xml
      run: |
        NEW_VERSION="${{ github.event.inputs.snapshot_version }}"
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add pom.xml
        git commit -m "Update version to $NEW_VERSION"
        git push --set-upstream origin dynamic-vars-tasks

    - name: Maven Build
      run: mvn clean install

    - name: Create Pull Request
      id: create-pr
      uses: create-pull-request@v3
      with:
        branch: dynamic-vars-tasks
        base: main
        title: "Update to ${{ github.event.inputs.snapshot_version }}"
        body: "This pull request updates the version and builds the project."

  codeql-analysis:
    needs: build-and-update
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  auto-merge:
    needs: codeql-analysis
    if: github.event.pull_request.head.ref == 'dynamic-vars-tasks'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    # - name: Merge PR
    #   run: |
    #     git fetch origin dynamic-vars-tasks
    #     git merge --ff-only origin/dynamic-vars-tasks
    #     git push origin main
