name: Build and PR with CodeQL Scan
on: workflow_dispatch

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Define new version
        run: echo "NEW_VERSION=1.0.24" >> $GITHUB_ENV

      - name: Update version for swagger-petstore in pom.xml
        run: |
          # Update the version for the swagger-petstore artifact only
          sed -i -E '/<artifactId>swagger-petstore<\/artifactId>/,/<\/version>/ s|<version>[0-9A-Za-z.-]*</version>|<version>'"$NEW_VERSION"'</version>|' pom.xml

      - name: Check if pom.xml was modified
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected in pom.xml"
          else
            echo "No changes detected in pom.xml"
            exit 1
          fi

      - name: Commit version change
        run: |
          git add pom.xml
          git commit -m "Update version to $NEW_VERSION"
          git push origin master
