name: Maven Build and Update Version

on:
  push:
    branches:
      - main  # or any other branch you want to target

jobs:
  build-and-update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Maven Clean Install
      run: mvn clean install

    - name: Update version in pom.xml
      run: |
        sed -i 's/<version>.*<\/version>/<version>1.0.1-SNAPSHOT<\/version>/g' pom.xml

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pom.xml
        git commit -m "Update version in pom.xml"
        git push
